// This code is generated by codegen command. Do not edit.
//
// As we cannot directly call a C function pointer from Go code
// we need to create C wrapper functions around ompapi pointers
// which will be used by Go code.

#include "include/wrappers.h"

struct OMPAPI_t* ompapi;

// Actor functions

void* Actor_Create(int model, float x, float y, float z, float rot, int* id) {
    return ompapi->Actor.Create(model, x, y, z, rot, id);
}

bool Actor_Destroy(void* actor) {
    return ompapi->Actor.Destroy(actor);
}

void* Actor_FromID(int actorid) {
    return ompapi->Actor.FromID(actorid);
}

int Actor_GetID(void* actor) {
    return ompapi->Actor.GetID(actor);
}

bool Actor_IsStreamedInFor(void* actor, void* player) {
    return ompapi->Actor.IsStreamedInFor(actor, player);
}

bool Actor_SetVirtualWorld(void* actor, int vw) {
    return ompapi->Actor.SetVirtualWorld(actor, vw);
}

int Actor_GetVirtualWorld(void* actor) {
    return ompapi->Actor.GetVirtualWorld(actor);
}

bool Actor_ApplyAnimation(void* actor, const char* name, const char* library, float delta, bool loop, bool lockX, bool lockY, bool freeze, int time) {
    return ompapi->Actor.ApplyAnimation(actor, name, library, delta, loop, lockX, lockY, freeze, time);
}

bool Actor_ClearAnimations(void* actor) {
    return ompapi->Actor.ClearAnimations(actor);
}

bool Actor_SetPos(void* actor, float x, float y, float z) {
    return ompapi->Actor.SetPos(actor, x, y, z);
}

bool Actor_GetPos(void* actor, float* x, float* y, float* z) {
    return ompapi->Actor.GetPos(actor, x, y, z);
}

bool Actor_SetFacingAngle(void* actor, float angle) {
    return ompapi->Actor.SetFacingAngle(actor, angle);
}

float Actor_GetFacingAngle(void* actor) {
    return ompapi->Actor.GetFacingAngle(actor);
}

bool Actor_SetHealth(void* actor, float hp) {
    return ompapi->Actor.SetHealth(actor, hp);
}

float Actor_GetHealth(void* actor) {
    return ompapi->Actor.GetHealth(actor);
}

bool Actor_SetInvulnerable(void* actor, bool toggle) {
    return ompapi->Actor.SetInvulnerable(actor, toggle);
}

bool Actor_IsInvulnerable(void* actor) {
    return ompapi->Actor.IsInvulnerable(actor);
}

bool Actor_IsValid(void* actor) {
    return ompapi->Actor.IsValid(actor);
}

bool Actor_SetSkin(void* actor, int skin) {
    return ompapi->Actor.SetSkin(actor, skin);
}

int Actor_GetSkin(void* actor) {
    return ompapi->Actor.GetSkin(actor);
}

bool Actor_GetAnimation(void* actor, CAPIStringView* library, CAPIStringView* name, float* delta, bool* loop, bool* lockX, bool* lockY, bool* freeze, int* time) {
    return ompapi->Actor.GetAnimation(actor, library, name, delta, loop, lockX, lockY, freeze, time);
}

bool Actor_GetSpawnInfo(void* actor, float* x, float* y, float* z, float* angle, int* skin) {
    return ompapi->Actor.GetSpawnInfo(actor, x, y, z, angle, skin);
}


// Checkpoint functions

bool Checkpoint_Set(void* player, float x, float y, float z, float radius) {
    return ompapi->Checkpoint.Set(player, x, y, z, radius);
}

bool Checkpoint_Disable(void* player) {
    return ompapi->Checkpoint.Disable(player);
}

bool Checkpoint_IsPlayerIn(void* player) {
    return ompapi->Checkpoint.IsPlayerIn(player);
}

bool Checkpoint_IsActive(void* player) {
    return ompapi->Checkpoint.IsActive(player);
}

bool Checkpoint_Get(void* player, float* x, float* y, float* z, float* radius) {
    return ompapi->Checkpoint.Get(player, x, y, z, radius);
}


// RaceCheckpoint functions

bool RaceCheckpoint_Set(void* player, int type, float x, float y, float z, float nextX, float nextY, float nextZ, float radius) {
    return ompapi->RaceCheckpoint.Set(player, type, x, y, z, nextX, nextY, nextZ, radius);
}

bool RaceCheckpoint_Disable(void* player) {
    return ompapi->RaceCheckpoint.Disable(player);
}

bool RaceCheckpoint_IsPlayerIn(void* player) {
    return ompapi->RaceCheckpoint.IsPlayerIn(player);
}

bool RaceCheckpoint_IsActive(void* player) {
    return ompapi->RaceCheckpoint.IsActive(player);
}

bool RaceCheckpoint_Get(void* player, float* x, float* y, float* z, float* nextX, float* nextY, float* nextZ, float* radius) {
    return ompapi->RaceCheckpoint.Get(player, x, y, z, nextX, nextY, nextZ, radius);
}


// Class functions

void* Class_Add(uint8_t team, int skin, float x, float y, float z, float angle, uint8_t weapon1, uint32_t ammo1, uint8_t weapon2, uint32_t ammo2, uint8_t weapon3, uint32_t ammo3, int* id) {
    return ompapi->Class.Add(team, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3, id);
}

void* Class_FromID(int classid) {
    return ompapi->Class.FromID(classid);
}

int Class_GetID(void* cls) {
    return ompapi->Class.GetID(cls);
}

int Class_Count() {
    return ompapi->Class.Count();
}

bool Class_GetData(void* classptr, uint8_t* teamid, int* skin, float* x, float* y, float* z, float* angle, uint8_t* weapon1, uint32_t* weapon1_ammo, uint8_t* weapon2, uint32_t* weapon2_ammo, uint8_t* weapon3, uint32_t* weapon3_ammo) {
    return ompapi->Class.GetData(classptr, teamid, skin, x, y, z, angle, weapon1, weapon1_ammo, weapon2, weapon2_ammo, weapon3, weapon3_ammo);
}

bool Class_Edit(void* classptr, uint8_t teamid, int skin, float x, float y, float z, float angle, uint8_t weapon1, uint32_t ammo1, uint8_t weapon2, uint32_t ammo2, uint8_t weapon3, uint32_t ammo3) {
    return ompapi->Class.Edit(classptr, teamid, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3);
}


// Player functions

bool Player_SetSpawnInfo(void* player, uint8_t team, int skin, float x, float y, float z, float angle, uint8_t weapon1, uint32_t ammo1, uint8_t weapon2, uint32_t ammo2, uint8_t weapon3, uint32_t ammo3) {
    return ompapi->Player.SetSpawnInfo(player, team, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3);
}

bool Player_GetSpawnInfo(void* player, uint8_t* team, int* skin, float* x, float* y, float* z, float* angle, uint8_t* weapon1, uint32_t* ammo1, uint8_t* weapon2, uint32_t* ammo2, uint8_t* weapon3, uint32_t* ammo3) {
    return ompapi->Player.GetSpawnInfo(player, team, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3);
}

int Player_GetNetworkStats(void* player, CAPIStringView* output) {
    return ompapi->Player.GetNetworkStats(player, output);
}

int Player_NetStatsBytesReceived(void* player) {
    return ompapi->Player.NetStatsBytesReceived(player);
}

int Player_NetStatsBytesSent(void* player) {
    return ompapi->Player.NetStatsBytesSent(player);
}

int Player_NetStatsConnectionStatus(void* player) {
    return ompapi->Player.NetStatsConnectionStatus(player);
}

int Player_NetStatsGetConnectedTime(void* player) {
    return ompapi->Player.NetStatsGetConnectedTime(player);
}

bool Player_NetStatsGetIpPort(void* player, CAPIStringView* output) {
    return ompapi->Player.NetStatsGetIpPort(player, output);
}

int Player_NetStatsMessagesReceived(void* player) {
    return ompapi->Player.NetStatsMessagesReceived(player);
}

int Player_NetStatsMessagesRecvPerSecond(void* player) {
    return ompapi->Player.NetStatsMessagesRecvPerSecond(player);
}

int Player_NetStatsMessagesSent(void* player) {
    return ompapi->Player.NetStatsMessagesSent(player);
}

float Player_NetStatsPacketLossPercent(void* player) {
    return ompapi->Player.NetStatsPacketLossPercent(player);
}

int Player_GetCustomSkin(void* player) {
    return ompapi->Player.GetCustomSkin(player);
}

int Player_GetDialog(void* player) {
    return ompapi->Player.GetDialog(player);
}

bool Player_GetDialogData(void* player, int* dialogid, int* style, CAPIStringView* title, CAPIStringView* body, CAPIStringView* button1, CAPIStringView* button2) {
    return ompapi->Player.GetDialogData(player, dialogid, style, title, body, button1, button2);
}

void* Player_GetMenu(void* player) {
    return ompapi->Player.GetMenu(player);
}

void* Player_GetSurfingPlayerObject(void* player) {
    return ompapi->Player.GetSurfingPlayerObject(player);
}

void* Player_GetCameraTargetPlayerObject(void* player) {
    return ompapi->Player.GetCameraTargetPlayerObject(player);
}

void* Player_FromID(int playerid) {
    return ompapi->Player.FromID(playerid);
}

int Player_GetID(void* player) {
    return ompapi->Player.GetID(player);
}

bool Player_SendClientMessage(void* player, uint32_t color, const char* text) {
    return ompapi->Player.SendClientMessage(player, color, text);
}

bool Player_SetCameraPos(void* player, float x, float y, float z) {
    return ompapi->Player.SetCameraPos(player, x, y, z);
}

bool Player_SetDrunkLevel(void* player, int level) {
    return ompapi->Player.SetDrunkLevel(player, level);
}

bool Player_SetInterior(void* player, int interior) {
    return ompapi->Player.SetInterior(player, interior);
}

bool Player_SetWantedLevel(void* player, int level) {
    return ompapi->Player.SetWantedLevel(player, level);
}

bool Player_SetWeather(void* player, int weather) {
    return ompapi->Player.SetWeather(player, weather);
}

int Player_GetWeather(void* player) {
    return ompapi->Player.GetWeather(player);
}

bool Player_SetSkin(void* player, int skin) {
    return ompapi->Player.SetSkin(player, skin);
}

bool Player_SetShopName(void* player, const char* name) {
    return ompapi->Player.SetShopName(player, name);
}

bool Player_GiveMoney(void* player, int amount) {
    return ompapi->Player.GiveMoney(player, amount);
}

bool Player_SetCameraLookAt(void* player, float x, float y, float z, int cutType) {
    return ompapi->Player.SetCameraLookAt(player, x, y, z, cutType);
}

bool Player_SetCameraBehind(void* player) {
    return ompapi->Player.SetCameraBehind(player);
}

bool Player_CreateExplosion(void* player, float x, float y, float z, int type, float radius) {
    return ompapi->Player.CreateExplosion(player, x, y, z, type, radius);
}

bool Player_PlayAudioStream(void* player, const char* url, float x, float y, float z, float distance, bool usePos) {
    return ompapi->Player.PlayAudioStream(player, url, x, y, z, distance, usePos);
}

bool Player_StopAudioStream(void* player) {
    return ompapi->Player.StopAudioStream(player);
}

bool Player_ToggleWidescreen(void* player, bool enable) {
    return ompapi->Player.ToggleWidescreen(player, enable);
}

bool Player_IsWidescreenToggled(void* player) {
    return ompapi->Player.IsWidescreenToggled(player);
}

bool Player_SetHealth(void* player, float health) {
    return ompapi->Player.SetHealth(player, health);
}

float Player_GetHealth(void* player) {
    return ompapi->Player.GetHealth(player);
}

bool Player_SetArmor(void* player, float armor) {
    return ompapi->Player.SetArmor(player, armor);
}

float Player_GetArmor(void* player) {
    return ompapi->Player.GetArmor(player);
}

bool Player_SetTeam(void* player, int team) {
    return ompapi->Player.SetTeam(player, team);
}

int Player_GetTeam(void* player) {
    return ompapi->Player.GetTeam(player);
}

bool Player_SetScore(void* player, int score) {
    return ompapi->Player.SetScore(player, score);
}

int Player_GetScore(void* player) {
    return ompapi->Player.GetScore(player);
}

int Player_GetSkin(void* player) {
    return ompapi->Player.GetSkin(player);
}

bool Player_SetColor(void* player, uint32_t color) {
    return ompapi->Player.SetColor(player, color);
}

uint32_t Player_GetColor(void* player) {
    return ompapi->Player.GetColor(player);
}

uint32_t Player_GetDefaultColor(void* player) {
    return ompapi->Player.GetDefaultColor(player);
}

int Player_GetDrunkLevel(void* player) {
    return ompapi->Player.GetDrunkLevel(player);
}

bool Player_GiveWeapon(void* player, int weapon, int ammo) {
    return ompapi->Player.GiveWeapon(player, weapon, ammo);
}

bool Player_RemoveWeapon(void* player, int weapon) {
    return ompapi->Player.RemoveWeapon(player, weapon);
}

int Player_GetMoney(void* player) {
    return ompapi->Player.GetMoney(player);
}

bool Player_ResetMoney(void* player) {
    return ompapi->Player.ResetMoney(player);
}

int Player_SetName(void* player, const char* name) {
    return ompapi->Player.SetName(player, name);
}

int Player_GetName(void* player, CAPIStringView* name) {
    return ompapi->Player.GetName(player, name);
}

int Player_GetState(void* player) {
    return ompapi->Player.GetState(player);
}

int Player_GetPing(void* player) {
    return ompapi->Player.GetPing(player);
}

int Player_GetWeapon(void* player) {
    return ompapi->Player.GetWeapon(player);
}

bool Player_SetTime(void* player, int hour, int minute) {
    return ompapi->Player.SetTime(player, hour, minute);
}

bool Player_GetTime(void* player, int* hour, int* minute) {
    return ompapi->Player.GetTime(player, hour, minute);
}

bool Player_ToggleClock(void* player, bool enable) {
    return ompapi->Player.ToggleClock(player, enable);
}

bool Player_HasClock(void* player) {
    return ompapi->Player.HasClock(player);
}

bool Player_ForceClassSelection(void* player) {
    return ompapi->Player.ForceClassSelection(player);
}

int Player_GetWantedLevel(void* player) {
    return ompapi->Player.GetWantedLevel(player);
}

bool Player_SetFightingStyle(void* player, int style) {
    return ompapi->Player.SetFightingStyle(player, style);
}

int Player_GetFightingStyle(void* player) {
    return ompapi->Player.GetFightingStyle(player);
}

bool Player_SetVelocity(void* player, float x, float y, float z) {
    return ompapi->Player.SetVelocity(player, x, y, z);
}

bool Player_GetVelocity(void* player, float* x, float* y, float* z) {
    return ompapi->Player.GetVelocity(player, x, y, z);
}

bool Player_GetCameraPos(void* player, float* x, float* y, float* z) {
    return ompapi->Player.GetCameraPos(player, x, y, z);
}

float Player_GetDistanceFromPoint(void* player, float x, float y, float z) {
    return ompapi->Player.GetDistanceFromPoint(player, x, y, z);
}

int Player_GetInterior(void* player) {
    return ompapi->Player.GetInterior(player);
}

bool Player_SetPos(void* player, float x, float y, float z) {
    return ompapi->Player.SetPos(player, x, y, z);
}

bool Player_GetPos(void* player, float* x, float* y, float* z) {
    return ompapi->Player.GetPos(player, x, y, z);
}

int Player_GetVirtualWorld(void* player) {
    return ompapi->Player.GetVirtualWorld(player);
}

bool Player_IsNPC(void* player) {
    return ompapi->Player.IsNPC(player);
}

bool Player_IsStreamedIn(void* player, void* other) {
    return ompapi->Player.IsStreamedIn(player, other);
}

bool Player_PlayGameSound(void* player, int sound, float x, float y, float z) {
    return ompapi->Player.PlayGameSound(player, sound, x, y, z);
}

bool Player_SpectatePlayer(void* player, void* target, int mode) {
    return ompapi->Player.SpectatePlayer(player, target, mode);
}

bool Player_SpectateVehicle(void* player, void* target, int mode) {
    return ompapi->Player.SpectateVehicle(player, target, mode);
}

bool Player_SetVirtualWorld(void* player, int vw) {
    return ompapi->Player.SetVirtualWorld(player, vw);
}

bool Player_SetWorldBounds(void* player, float xMax, float xMin, float yMax, float yMin) {
    return ompapi->Player.SetWorldBounds(player, xMax, xMin, yMax, yMin);
}

bool Player_ClearWorldBounds(void* player) {
    return ompapi->Player.ClearWorldBounds(player);
}

bool Player_GetWorldBounds(void* player, float* xmax, float* xmin, float* ymax, float* ymin) {
    return ompapi->Player.GetWorldBounds(player, xmax, xmin, ymax, ymin);
}

bool Player_ClearAnimations(void* player, int syncType) {
    return ompapi->Player.ClearAnimations(player, syncType);
}

bool Player_GetLastShotVectors(void* player, float* origin_x, float* origin_y, float* origin_z, float* hit_x, float* hit_y, float* hit_z) {
    return ompapi->Player.GetLastShotVectors(player, origin_x, origin_y, origin_z, hit_x, hit_y, hit_z);
}

void* Player_GetCameraTargetPlayer(void* player) {
    return ompapi->Player.GetCameraTargetPlayer(player);
}

void* Player_GetCameraTargetActor(void* player) {
    return ompapi->Player.GetCameraTargetActor(player);
}

void* Player_GetCameraTargetObject(void* player) {
    return ompapi->Player.GetCameraTargetObject(player);
}

void* Player_GetCameraTargetVehicle(void* player) {
    return ompapi->Player.GetCameraTargetVehicle(player);
}

bool Player_PutInVehicle(void* player, void* vehicle, int seat) {
    return ompapi->Player.PutInVehicle(player, vehicle, seat);
}

bool Player_RemoveBuilding(void* player, int model, float x, float y, float z, float radius) {
    return ompapi->Player.RemoveBuilding(player, model, x, y, z, radius);
}

int Player_GetBuildingsRemoved(void* player) {
    return ompapi->Player.GetBuildingsRemoved(player);
}

bool Player_RemoveFromVehicle(void* player, bool force) {
    return ompapi->Player.RemoveFromVehicle(player, force);
}

bool Player_RemoveMapIcon(void* player, int icon) {
    return ompapi->Player.RemoveMapIcon(player, icon);
}

bool Player_SetMapIcon(void* player, int iconID, float x, float y, float z, int type, uint32_t color, int style) {
    return ompapi->Player.SetMapIcon(player, iconID, x, y, z, type, color, style);
}

bool Player_ResetWeapons(void* player) {
    return ompapi->Player.ResetWeapons(player);
}

bool Player_SetAmmo(void* player, uint8_t id, uint32_t ammo) {
    return ompapi->Player.SetAmmo(player, id, ammo);
}

bool Player_SetArmedWeapon(void* player, uint8_t weapon) {
    return ompapi->Player.SetArmedWeapon(player, weapon);
}

bool Player_SetChatBubble(void* player, const char* text, uint32_t color, float drawdistance, int expiretime) {
    return ompapi->Player.SetChatBubble(player, text, color, drawdistance, expiretime);
}

bool Player_SetPosFindZ(void* player, float x, float y, float z) {
    return ompapi->Player.SetPosFindZ(player, x, y, z);
}

bool Player_SetSkillLevel(void* player, uint8_t weapon, int level) {
    return ompapi->Player.SetSkillLevel(player, weapon, level);
}

bool Player_SetSpecialAction(void* player, uint32_t action) {
    return ompapi->Player.SetSpecialAction(player, action);
}

bool Player_ShowNameTagForPlayer(void* player, void* other, bool enable) {
    return ompapi->Player.ShowNameTagForPlayer(player, other, enable);
}

bool Player_ToggleControllable(void* player, bool enable) {
    return ompapi->Player.ToggleControllable(player, enable);
}

bool Player_ToggleSpectating(void* player, bool enable) {
    return ompapi->Player.ToggleSpectating(player, enable);
}

bool Player_ApplyAnimation(void* player, const char* animlib, const char* animname, float delta, bool loop, bool lockX, bool lockY, bool freeze, uint32_t time, int sync) {
    return ompapi->Player.ApplyAnimation(player, animlib, animname, delta, loop, lockX, lockY, freeze, time, sync);
}

bool Player_GetAnimationName(int index, CAPIStringView* lib, CAPIStringView* name) {
    return ompapi->Player.GetAnimationName(index, lib, name);
}

bool Player_EditAttachedObject(void* player, int index) {
    return ompapi->Player.EditAttachedObject(player, index);
}

bool Player_EnableCameraTarget(void* player, bool enable) {
    return ompapi->Player.EnableCameraTarget(player, enable);
}

bool Player_EnableStuntBonus(void* player, bool enable) {
    return ompapi->Player.EnableStuntBonus(player, enable);
}

int Player_GetPlayerAmmo(void* player) {
    return ompapi->Player.GetPlayerAmmo(player);
}

int Player_GetAnimationIndex(void* player) {
    return ompapi->Player.GetAnimationIndex(player);
}

float Player_GetFacingAngle(void* player) {
    return ompapi->Player.GetFacingAngle(player);
}

int Player_GetIp(void* player, CAPIStringView* ip) {
    return ompapi->Player.GetIp(player, ip);
}

int Player_GetSpecialAction(void* player) {
    return ompapi->Player.GetSpecialAction(player);
}

int Player_GetVehicleID(void* player) {
    return ompapi->Player.GetVehicleID(player);
}

int Player_GetVehicleSeat(void* player) {
    return ompapi->Player.GetVehicleSeat(player);
}

bool Player_GetWeaponData(void* player, int slot, int* weaponid, int* ammo) {
    return ompapi->Player.GetWeaponData(player, slot, weaponid, ammo);
}

int Player_GetWeaponState(void* player) {
    return ompapi->Player.GetWeaponState(player);
}

bool Player_InterpolateCameraPos(void* player, float from_x, float from_y, float from_z, float to_x, float to_y, float to_z, int time, int cut) {
    return ompapi->Player.InterpolateCameraPos(player, from_x, from_y, from_z, to_x, to_y, to_z, time, cut);
}

bool Player_InterpolateCameraLookAt(void* player, float from_x, float from_y, float from_z, float to_x, float to_y, float to_z, int time, int cut) {
    return ompapi->Player.InterpolateCameraLookAt(player, from_x, from_y, from_z, to_x, to_y, to_z, time, cut);
}

bool Player_IsPlayerAttachedObjectSlotUsed(void* player, int index) {
    return ompapi->Player.IsPlayerAttachedObjectSlotUsed(player, index);
}

bool Player_AttachCameraToObject(void* player, void* object) {
    return ompapi->Player.AttachCameraToObject(player, object);
}

bool Player_AttachCameraToPlayerObject(void* player, void* object) {
    return ompapi->Player.AttachCameraToPlayerObject(player, object);
}

float Player_GetCameraAspectRatio(void* player) {
    return ompapi->Player.GetCameraAspectRatio(player);
}

bool Player_GetCameraFrontVector(void* player, float* x, float* y, float* z) {
    return ompapi->Player.GetCameraFrontVector(player, x, y, z);
}

int Player_GetCameraMode(void* player) {
    return ompapi->Player.GetCameraMode(player);
}

bool Player_GetKeys(void* player, int* keys, int* updown, int* leftright) {
    return ompapi->Player.GetKeys(player, keys, updown, leftright);
}

void* Player_GetSurfingVehicle(void* player) {
    return ompapi->Player.GetSurfingVehicle(player);
}

void* Player_GetSurfingObject(void* player) {
    return ompapi->Player.GetSurfingObject(player);
}

void* Player_GetTargetPlayer(void* player) {
    return ompapi->Player.GetTargetPlayer(player);
}

void* Player_GetTargetActor(void* player) {
    return ompapi->Player.GetTargetActor(player);
}

bool Player_IsInVehicle(void* player, void* targetVehicle) {
    return ompapi->Player.IsInVehicle(player, targetVehicle);
}

bool Player_IsInAnyVehicle(void* player) {
    return ompapi->Player.IsInAnyVehicle(player);
}

bool Player_IsInRangeOfPoint(void* player, float range, float x, float y, float z) {
    return ompapi->Player.IsInRangeOfPoint(player, range, x, y, z);
}

bool Player_PlayCrimeReport(void* player, void* suspect, int crime) {
    return ompapi->Player.PlayCrimeReport(player, suspect, crime);
}

bool Player_RemoveAttachedObject(void* player, int index) {
    return ompapi->Player.RemoveAttachedObject(player, index);
}

bool Player_SetAttachedObject(void* player, int index, int modelid, int bone, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ, float scaleX, float scaleY, float scaleZ, uint32_t materialcolor1, uint32_t materialcolor2) {
    return ompapi->Player.SetAttachedObject(player, index, modelid, bone, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, scaleX, scaleY, scaleZ, materialcolor1, materialcolor2);
}

bool Player_GetAttachedObject(void* player, int index, int* modelid, int* bone, float* offsetX, float* offsetY, float* offsetZ, float* rotationX, float* rotationY, float* rotationZ, float* scaleX, float* scaleY, float* scaleZ, int* materialcolor1, int* materialcolor2) {
    return ompapi->Player.GetAttachedObject(player, index, modelid, bone, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, scaleX, scaleY, scaleZ, materialcolor1, materialcolor2);
}

bool Player_SetFacingAngle(void* player, float angle) {
    return ompapi->Player.SetFacingAngle(player, angle);
}

bool Player_SetMarkerForPlayer(void* player, void* other, uint32_t color) {
    return ompapi->Player.SetMarkerForPlayer(player, other, color);
}

uint32_t Player_GetMarkerForPlayer(void* player, void* other) {
    return ompapi->Player.GetMarkerForPlayer(player, other);
}

bool Player_AllowTeleport(void* player, bool allow) {
    return ompapi->Player.AllowTeleport(player, allow);
}

bool Player_IsTeleportAllowed(void* player) {
    return ompapi->Player.IsTeleportAllowed(player);
}

bool Player_DisableRemoteVehicleCollisions(void* player, bool disable) {
    return ompapi->Player.DisableRemoteVehicleCollisions(player, disable);
}

float Player_GetCameraZoom(void* player) {
    return ompapi->Player.GetCameraZoom(player);
}

bool Player_SelectTextDraw(void* player, uint32_t hoverColour) {
    return ompapi->Player.SelectTextDraw(player, hoverColour);
}

bool Player_CancelSelectTextDraw(void* player) {
    return ompapi->Player.CancelSelectTextDraw(player);
}

bool Player_SendClientCheck(void* player, int actionType, int address, int offset, int count) {
    return ompapi->Player.SendClientCheck(player, actionType, address, offset, count);
}

bool Player_Spawn(void* player) {
    return ompapi->Player.Spawn(player);
}

bool Player_GPCI(void* player, CAPIStringView* gpci) {
    return ompapi->Player.GPCI(player, gpci);
}

bool Player_IsAdmin(void* player) {
    return ompapi->Player.IsAdmin(player);
}

bool Player_Kick(void* player) {
    return ompapi->Player.Kick(player);
}

bool Player_ShowGameText(void* player, const char* text, int time, int style) {
    return ompapi->Player.ShowGameText(player, text, time, style);
}

bool Player_HideGameText(void* player, int style) {
    return ompapi->Player.HideGameText(player, style);
}

bool Player_HasGameText(void* player, int style) {
    return ompapi->Player.HasGameText(player, style);
}

bool Player_GetGameText(void* player, int style, CAPIStringView* message, int* time, int* remaining) {
    return ompapi->Player.GetGameText(player, style, message, time, remaining);
}

bool Player_Ban(void* player) {
    return ompapi->Player.Ban(player);
}

bool Player_BanEx(void* player, const char* reason) {
    return ompapi->Player.BanEx(player, reason);
}

bool Player_SendDeathMessage(void* player, void* killer, void* killee, int weapon) {
    return ompapi->Player.SendDeathMessage(player, killer, killee, weapon);
}

bool Player_SendMessageToPlayer(void* player, void* sender, const char* message) {
    return ompapi->Player.SendMessageToPlayer(player, sender, message);
}

int Player_GetVersion(void* player, CAPIStringView* version) {
    return ompapi->Player.GetVersion(player, version);
}

int Player_GetSkillLevel(void* player, int skill) {
    return ompapi->Player.GetSkillLevel(player, skill);
}

float Player_GetZAim(void* player) {
    return ompapi->Player.GetZAim(player);
}

bool Player_GetSurfingOffsets(void* player, float* offsetX, float* offsetY, float* offsetZ) {
    return ompapi->Player.GetSurfingOffsets(player, offsetX, offsetY, offsetZ);
}

bool Player_GetRotationQuat(void* player, float* x, float* y, float* z, float* w) {
    return ompapi->Player.GetRotationQuat(player, x, y, z, w);
}

int Player_GetPlayerSpectateID(void* player) {
    return ompapi->Player.GetPlayerSpectateID(player);
}

int Player_GetSpectateType(void* player) {
    return ompapi->Player.GetSpectateType(player);
}

uint32_t Player_GetRawIp(void* player) {
    return ompapi->Player.GetRawIp(player);
}

bool Player_SetGravity(void* player, float gravity) {
    return ompapi->Player.SetGravity(player, gravity);
}

float Player_GetGravity(void* player) {
    return ompapi->Player.GetGravity(player);
}

bool Player_SetAdmin(void* player, bool set) {
    return ompapi->Player.SetAdmin(player, set);
}

bool Player_IsSpawned(void* player) {
    return ompapi->Player.IsSpawned(player);
}

bool Player_IsControllable(void* player) {
    return ompapi->Player.IsControllable(player);
}

bool Player_IsCameraTargetEnabled(void* player) {
    return ompapi->Player.IsCameraTargetEnabled(player);
}

bool Player_ToggleGhostMode(void* player, bool toggle) {
    return ompapi->Player.ToggleGhostMode(player, toggle);
}

bool Player_GetGhostMode(void* player) {
    return ompapi->Player.GetGhostMode(player);
}

bool Player_AllowWeapons(void* player, bool allow) {
    return ompapi->Player.AllowWeapons(player, allow);
}

bool Player_AreWeaponsAllowed(void* player) {
    return ompapi->Player.AreWeaponsAllowed(player);
}

bool Player_IsPlayerUsingOfficialClient(void* player) {
    return ompapi->Player.IsPlayerUsingOfficialClient(player);
}

int Player_GetAnimationFlags(void* player) {
    return ompapi->Player.GetAnimationFlags(player);
}

bool Player_IsInDriveByMode(void* player) {
    return ompapi->Player.IsInDriveByMode(player);
}

bool Player_IsCuffed(void* player) {
    return ompapi->Player.IsCuffed(player);
}

bool Player_IsInModShop(void* player) {
    return ompapi->Player.IsInModShop(player);
}

int Player_GetSirenState(void* player) {
    return ompapi->Player.GetSirenState(player);
}

int Player_GetLandingGearState(void* player) {
    return ompapi->Player.GetLandingGearState(player);
}

uint32_t Player_GetHydraReactorAngle(void* player) {
    return ompapi->Player.GetHydraReactorAngle(player);
}

float Player_GetTrainSpeed(void* player) {
    return ompapi->Player.GetTrainSpeed(player);
}


// Component functions

void* Component_Create(uint64_t uid, const char* name, ComponentVersion version, void* onReadyCB, void* onResetCB, void* onFreeCB) {
    return ompapi->Component.Create(uid, name, version, onReadyCB, onResetCB, onFreeCB);
}


// Config functions

bool Config_GetAsBool(const char* cvar) {
    return ompapi->Config.GetAsBool(cvar);
}

int Config_GetAsInt(const char* cvar) {
    return ompapi->Config.GetAsInt(cvar);
}

float Config_GetAsFloat(const char* cvar) {
    return ompapi->Config.GetAsFloat(cvar);
}

int Config_GetAsString(const char* cvar, CAPIStringView* output) {
    return ompapi->Config.GetAsString(cvar, output);
}


// Core functions

uint32_t Core_TickCount() {
    return ompapi->Core.TickCount();
}

int Core_MaxPlayers() {
    return ompapi->Core.MaxPlayers();
}

bool Core_Log(const char* text) {
    return ompapi->Core.Log(text);
}

bool Core_IsAdminTeleportAllowed() {
    return ompapi->Core.IsAdminTeleportAllowed();
}

bool Core_AllowAdminTeleport(bool allow) {
    return ompapi->Core.AllowAdminTeleport(allow);
}

bool Core_AreAllAnimationsEnabled() {
    return ompapi->Core.AreAllAnimationsEnabled();
}

bool Core_EnableAllAnimations(bool allow) {
    return ompapi->Core.EnableAllAnimations(allow);
}

bool Core_IsAnimationLibraryValid(const char* name) {
    return ompapi->Core.IsAnimationLibraryValid(name);
}

bool Core_AreInteriorWeaponsAllowed() {
    return ompapi->Core.AreInteriorWeaponsAllowed();
}

bool Core_AllowInteriorWeapons(bool allow) {
    return ompapi->Core.AllowInteriorWeapons(allow);
}

bool Core_BlockIpAddress(const char* ipAddress, int timeMS) {
    return ompapi->Core.BlockIpAddress(ipAddress, timeMS);
}

bool Core_UnBlockIpAddress(const char* ipAddress) {
    return ompapi->Core.UnBlockIpAddress(ipAddress);
}

bool Core_DisableEntryExitMarkers() {
    return ompapi->Core.DisableEntryExitMarkers();
}

bool Core_DisableNameTagsLOS() {
    return ompapi->Core.DisableNameTagsLOS();
}

bool Core_EnableZoneNames(bool enable) {
    return ompapi->Core.EnableZoneNames(enable);
}

bool Core_ShowGameTextForAll(const char* msg, int time, int style) {
    return ompapi->Core.ShowGameTextForAll(msg, time, style);
}

bool Core_HideGameTextForAll(int style) {
    return ompapi->Core.HideGameTextForAll(style);
}

int Core_NetworkStats(CAPIStringView* output) {
    return ompapi->Core.NetworkStats(output);
}

int Core_ServerTickRate() {
    return ompapi->Core.ServerTickRate();
}

bool Core_GetWeaponName(int weaponid, CAPIStringView* output) {
    return ompapi->Core.GetWeaponName(weaponid, output);
}

bool Core_SetChatRadius(float globalChatRadius) {
    return ompapi->Core.SetChatRadius(globalChatRadius);
}

bool Core_SetMarkerRadius(float playerMarkerRadius) {
    return ompapi->Core.SetMarkerRadius(playerMarkerRadius);
}

bool Core_SendRconCommand(const char* command) {
    return ompapi->Core.SendRconCommand(command);
}

bool Core_SetDeathDropAmount(int amount) {
    return ompapi->Core.SetDeathDropAmount(amount);
}

bool Core_GameMode_SetText(const char* string) {
    return ompapi->Core.GameMode_SetText(string);
}

bool Core_SetGravity(float gravity) {
    return ompapi->Core.SetGravity(gravity);
}

float Core_GetGravity() {
    return ompapi->Core.GetGravity();
}

bool Core_SetNameTagsDrawDistance(float distance) {
    return ompapi->Core.SetNameTagsDrawDistance(distance);
}

bool Core_SetWeather(int weatherid) {
    return ompapi->Core.SetWeather(weatherid);
}

bool Core_SetWorldTime(int hour) {
    return ompapi->Core.SetWorldTime(hour);
}

bool Core_ShowNameTags(bool show) {
    return ompapi->Core.ShowNameTags(show);
}

bool Core_ShowPlayerMarkers(int mode) {
    return ompapi->Core.ShowPlayerMarkers(mode);
}

bool Core_UsePedAnims() {
    return ompapi->Core.UsePedAnims();
}

int Core_GetWeather() {
    return ompapi->Core.GetWeather();
}

int Core_GetWorldTime() {
    return ompapi->Core.GetWorldTime();
}

bool Core_ToggleChatTextReplacement(bool enable) {
    return ompapi->Core.ToggleChatTextReplacement(enable);
}

bool Core_IsChatTextReplacementToggled() {
    return ompapi->Core.IsChatTextReplacementToggled();
}

bool Core_IsNickNameValid(const char* name) {
    return ompapi->Core.IsNickNameValid(name);
}

bool Core_AllowNickNameCharacter(int character, bool allow) {
    return ompapi->Core.AllowNickNameCharacter(character, allow);
}

bool Core_IsNickNameCharacterAllowed(int character) {
    return ompapi->Core.IsNickNameCharacterAllowed(character);
}

bool Core_ClearBanList() {
    return ompapi->Core.ClearBanList();
}

bool Core_IsIpAddressBanned(const char* ip) {
    return ompapi->Core.IsIpAddressBanned(ip);
}

int Core_GetWeaponSlot(uint8_t weapon) {
    return ompapi->Core.GetWeaponSlot(weapon);
}

bool Core_AddRule(const char* name, const char* value) {
    return ompapi->Core.AddRule(name, value);
}

bool Core_IsValidRule(const char* name) {
    return ompapi->Core.IsValidRule(name);
}

bool Core_RemoveRule(const char* name) {
    return ompapi->Core.RemoveRule(name);
}


// NPC functions

bool NPC_Connect(const char* name, const char* script) {
    return ompapi->NPC.Connect(name, script);
}


// CustomModel functions

bool CustomModel_AddCharModel(int baseid, int newid, const char* dff, const char* textureLibrary) {
    return ompapi->CustomModel.AddCharModel(baseid, newid, dff, textureLibrary);
}

bool CustomModel_AddSimpleModel(int virtualWorld, int baseid, int newid, const char* dff, const char* textureLibrary) {
    return ompapi->CustomModel.AddSimpleModel(virtualWorld, baseid, newid, dff, textureLibrary);
}

bool CustomModel_AddSimpleModelTimed(int virtualWorld, int baseid, int newid, const char* dff, const char* textureLibrary, int timeOn, int timeOff) {
    return ompapi->CustomModel.AddSimpleModelTimed(virtualWorld, baseid, newid, dff, textureLibrary, timeOn, timeOff);
}

bool CustomModel_RedirectDownload(void* player, const char* url) {
    return ompapi->CustomModel.RedirectDownload(player, url);
}

int CustomModel_FindModelFileNameFromCRC(int crc, CAPIStringView* output) {
    return ompapi->CustomModel.FindModelFileNameFromCRC(crc, output);
}

bool CustomModel_IsValid(int modelId) {
    return ompapi->CustomModel.IsValid(modelId);
}

bool CustomModel_GetPath(int modelId, CAPIStringView* dffPath, CAPIStringView* txdPath) {
    return ompapi->CustomModel.GetPath(modelId, dffPath, txdPath);
}


// Dialog functions

bool Dialog_Show(void* player, int dialog, int style, const char* title, const char* body, const char* button1, const char* button2) {
    return ompapi->Dialog.Show(player, dialog, style, title, body, button1, button2);
}

bool Dialog_Hide(void* player) {
    return ompapi->Dialog.Hide(player);
}


// Event functions

bool Event_AddHandler(const char* name, int priority, void* callback) {
    return ompapi->Event.AddHandler(name, priority, callback);
}

bool Event_RemoveHandler(const char* name, int priority, void* callback) {
    return ompapi->Event.RemoveHandler(name, priority, callback);
}

bool Event_RemoveAllHandlers(const char* name, int priority) {
    return ompapi->Event.RemoveAllHandlers(name, priority);
}


// GangZone functions

void* GangZone_Create(float minx, float miny, float maxx, float maxy, int* id) {
    return ompapi->GangZone.Create(minx, miny, maxx, maxy, id);
}

bool GangZone_Destroy(void* gangzone) {
    return ompapi->GangZone.Destroy(gangzone);
}

void* GangZone_FromID(int gangzoneid) {
    return ompapi->GangZone.FromID(gangzoneid);
}

int GangZone_GetID(void* gangzone) {
    return ompapi->GangZone.GetID(gangzone);
}

bool GangZone_ShowForPlayer(void* player, void* gangzone, uint32_t color) {
    return ompapi->GangZone.ShowForPlayer(player, gangzone, color);
}

bool GangZone_ShowForAll(void* gangzone, uint32_t color) {
    return ompapi->GangZone.ShowForAll(gangzone, color);
}

bool GangZone_HideForPlayer(void* player, void* gangzone) {
    return ompapi->GangZone.HideForPlayer(player, gangzone);
}

bool GangZone_HideForAll(void* gangzone) {
    return ompapi->GangZone.HideForAll(gangzone);
}

bool GangZone_FlashForPlayer(void* player, void* gangzone, uint32_t color) {
    return ompapi->GangZone.FlashForPlayer(player, gangzone, color);
}

bool GangZone_FlashForAll(void* gangzone, uint32_t color) {
    return ompapi->GangZone.FlashForAll(gangzone, color);
}

bool GangZone_StopFlashForPlayer(void* player, void* gangzone) {
    return ompapi->GangZone.StopFlashForPlayer(player, gangzone);
}

bool GangZone_StopFlashForAll(void* gangzone) {
    return ompapi->GangZone.StopFlashForAll(gangzone);
}

bool GangZone_IsValid(void* gangzone) {
    return ompapi->GangZone.IsValid(gangzone);
}

bool GangZone_IsPlayerIn(void* player, void* gangzone) {
    return ompapi->GangZone.IsPlayerIn(player, gangzone);
}

bool GangZone_IsVisibleForPlayer(void* player, void* gangzone) {
    return ompapi->GangZone.IsVisibleForPlayer(player, gangzone);
}

int GangZone_GetColorForPlayer(void* player, void* gangzone) {
    return ompapi->GangZone.GetColorForPlayer(player, gangzone);
}

int GangZone_GetFlashColorForPlayer(void* player, void* gangzone) {
    return ompapi->GangZone.GetFlashColorForPlayer(player, gangzone);
}

bool GangZone_IsFlashingForPlayer(void* player, void* gangzone) {
    return ompapi->GangZone.IsFlashingForPlayer(player, gangzone);
}

bool GangZone_GetPos(void* gangzone, float* minx, float* miny, float* maxx, float* maxy) {
    return ompapi->GangZone.GetPos(gangzone, minx, miny, maxx, maxy);
}

bool GangZone_UseCheck(void* gangzone, bool enable) {
    return ompapi->GangZone.UseCheck(gangzone, enable);
}


// Menu functions

void* Menu_Create(const char* title, uint32_t columns, float x, float y, float column1Width, float column2Width, int* id) {
    return ompapi->Menu.Create(title, columns, x, y, column1Width, column2Width, id);
}

bool Menu_Destroy(void* menu) {
    return ompapi->Menu.Destroy(menu);
}

void* Menu_FromID(int menuid) {
    return ompapi->Menu.FromID(menuid);
}

int Menu_GetID(void* menu) {
    return ompapi->Menu.GetID(menu);
}

int Menu_AddItem(void* menu, uint8_t column, const char* text) {
    return ompapi->Menu.AddItem(menu, column, text);
}

bool Menu_SetColumnHeader(void* menu, uint8_t column, const char* headerTitle) {
    return ompapi->Menu.SetColumnHeader(menu, column, headerTitle);
}

bool Menu_ShowForPlayer(void* menu, void* player) {
    return ompapi->Menu.ShowForPlayer(menu, player);
}

bool Menu_HideForPlayer(void* menu, void* player) {
    return ompapi->Menu.HideForPlayer(menu, player);
}

bool Menu_Disable(void* menu) {
    return ompapi->Menu.Disable(menu);
}

bool Menu_DisableRow(void* menu, uint8_t row) {
    return ompapi->Menu.DisableRow(menu, row);
}

bool Menu_IsValid(void* menu) {
    return ompapi->Menu.IsValid(menu);
}

bool Menu_IsDisabled(void* menu) {
    return ompapi->Menu.IsDisabled(menu);
}

bool Menu_IsRowDisabled(void* menu, int row) {
    return ompapi->Menu.IsRowDisabled(menu, row);
}

int Menu_GetColumns(void* menu) {
    return ompapi->Menu.GetColumns(menu);
}

int Menu_GetItems(void* menu, int column) {
    return ompapi->Menu.GetItems(menu, column);
}

bool Menu_GetPos(void* menu, float* x, float* y) {
    return ompapi->Menu.GetPos(menu, x, y);
}

bool Menu_GetColumnWidth(void* menu, float* column1Width, float* column2Width) {
    return ompapi->Menu.GetColumnWidth(menu, column1Width, column2Width);
}

bool Menu_GetColumnHeader(void* menu, int column, CAPIStringView* header) {
    return ompapi->Menu.GetColumnHeader(menu, column, header);
}

bool Menu_GetItem(void* menu, int column, int row, CAPIStringView* item) {
    return ompapi->Menu.GetItem(menu, column, row, item);
}


// Object functions

void* Object_Create(int modelid, float x, float y, float z, float rotationX, float rotationY, float rotationZ, float drawDistance, int* id) {
    return ompapi->Object.Create(modelid, x, y, z, rotationX, rotationY, rotationZ, drawDistance, id);
}

bool Object_Destroy(void* object) {
    return ompapi->Object.Destroy(object);
}

void* Object_FromID(int objectid) {
    return ompapi->Object.FromID(objectid);
}

int Object_GetID(void* object) {
    return ompapi->Object.GetID(object);
}

bool Object_AttachToVehicle(void* object, void* vehicle, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ) {
    return ompapi->Object.AttachToVehicle(object, vehicle, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool Object_AttachToObject(void* object, void* objAttachedTo, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ, bool syncRotation) {
    return ompapi->Object.AttachToObject(object, objAttachedTo, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, syncRotation);
}

bool Object_AttachToPlayer(void* object, void* player, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ) {
    return ompapi->Object.AttachToPlayer(object, player, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool Object_SetPos(void* object, float x, float y, float z) {
    return ompapi->Object.SetPos(object, x, y, z);
}

bool Object_GetPos(void* object, float* x, float* y, float* z) {
    return ompapi->Object.GetPos(object, x, y, z);
}

bool Object_SetRot(void* object, float rotationX, float rotationY, float rotationZ) {
    return ompapi->Object.SetRot(object, rotationX, rotationY, rotationZ);
}

bool Object_GetRot(void* object, float* rotationX, float* rotationY, float* rotationZ) {
    return ompapi->Object.GetRot(object, rotationX, rotationY, rotationZ);
}

int Object_GetModel(void* object) {
    return ompapi->Object.GetModel(object);
}

bool Object_SetNoCameraCollision(void* object) {
    return ompapi->Object.SetNoCameraCollision(object);
}

bool Object_IsValid(void* object) {
    return ompapi->Object.IsValid(object);
}

int Object_Move(void* object, float x, float y, float z, float speed, float rotationX, float rotationY, float rotationZ) {
    return ompapi->Object.Move(object, x, y, z, speed, rotationX, rotationY, rotationZ);
}

bool Object_Stop(void* object) {
    return ompapi->Object.Stop(object);
}

bool Object_IsMoving(void* object) {
    return ompapi->Object.IsMoving(object);
}

bool Object_BeginEditing(void* player, void* object) {
    return ompapi->Object.BeginEditing(player, object);
}

bool Object_BeginSelecting(void* player) {
    return ompapi->Object.BeginSelecting(player);
}

bool Object_EndEditing(void* player) {
    return ompapi->Object.EndEditing(player);
}

bool Object_SetMaterial(void* object, int materialIndex, int modelId, const char* textureLibrary, const char* textureName, uint32_t materialColor) {
    return ompapi->Object.SetMaterial(object, materialIndex, modelId, textureLibrary, textureName, materialColor);
}

bool Object_SetMaterialText(void* object, const char* text, int materialIndex, int materialSize, const char* fontface, int fontsize, bool bold, uint32_t fontColor, uint32_t backgroundColor, int textalignment) {
    return ompapi->Object.SetMaterialText(object, text, materialIndex, materialSize, fontface, fontsize, bold, fontColor, backgroundColor, textalignment);
}

bool Object_SetDefaultCameraCollision(bool disable) {
    return ompapi->Object.SetDefaultCameraCollision(disable);
}

float Object_GetDrawDistance(void* object) {
    return ompapi->Object.GetDrawDistance(object);
}

float Object_GetMoveSpeed(void* object) {
    return ompapi->Object.GetMoveSpeed(object);
}

bool Object_GetMovingTargetPos(void* object, float* targetX, float* targetY, float* targetZ) {
    return ompapi->Object.GetMovingTargetPos(object, targetX, targetY, targetZ);
}

bool Object_GetMovingTargetRot(void* object, float* rotationX, float* rotationY, float* rotationZ) {
    return ompapi->Object.GetMovingTargetRot(object, rotationX, rotationY, rotationZ);
}

bool Object_GetAttachedData(void* object, int* parentVehicle, int* parentObject, int* parentPlayer) {
    return ompapi->Object.GetAttachedData(object, parentVehicle, parentObject, parentPlayer);
}

bool Object_GetAttachedOffset(void* object, float* offsetX, float* offsetY, float* offsetZ, float* rotationX, float* rotationY, float* rotationZ) {
    return ompapi->Object.GetAttachedOffset(object, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool Object_GetSyncRotation(void* object) {
    return ompapi->Object.GetSyncRotation(object);
}

bool Object_IsMaterialSlotUsed(void* object, int materialIndex) {
    return ompapi->Object.IsMaterialSlotUsed(object, materialIndex);
}

bool Object_GetMaterial(void* object, int materialIndex, int* modelid, CAPIStringView* textureLibrary, CAPIStringView* textureName, int* materialColor) {
    return ompapi->Object.GetMaterial(object, materialIndex, modelid, textureLibrary, textureName, materialColor);
}

bool Object_GetMaterialText(void* object, int materialIndex, CAPIStringView* text, int* materialSize, CAPIStringView* fontFace, int* fontSize, bool* bold, int* fontColor, int* backgroundColor, int* textAlignment) {
    return ompapi->Object.GetMaterialText(object, materialIndex, text, materialSize, fontFace, fontSize, bold, fontColor, backgroundColor, textAlignment);
}

bool Object_IsObjectNoCameraCollision(void* object) {
    return ompapi->Object.IsObjectNoCameraCollision(object);
}

uint8_t Object_GetType(void* player, int objectid) {
    return ompapi->Object.GetType(player, objectid);
}


// PlayerObject functions

void* PlayerObject_Create(void* player, int modelid, float x, float y, float z, float rotationX, float rotationY, float rotationZ, float drawDistance, int* id) {
    return ompapi->PlayerObject.Create(player, modelid, x, y, z, rotationX, rotationY, rotationZ, drawDistance, id);
}

bool PlayerObject_Destroy(void* player, void* object) {
    return ompapi->PlayerObject.Destroy(player, object);
}

void* PlayerObject_FromID(void* player, int objectid) {
    return ompapi->PlayerObject.FromID(player, objectid);
}

int PlayerObject_GetID(void* player, void* object) {
    return ompapi->PlayerObject.GetID(player, object);
}

bool PlayerObject_AttachToVehicle(void* player, void* object, void* vehicle, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ) {
    return ompapi->PlayerObject.AttachToVehicle(player, object, vehicle, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool PlayerObject_AttachToPlayer(void* player, void* object, void* playerAttachedTo, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ) {
    return ompapi->PlayerObject.AttachToPlayer(player, object, playerAttachedTo, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool PlayerObject_AttachToObject(void* player, void* object, void* attachedTo, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ) {
    return ompapi->PlayerObject.AttachToObject(player, object, attachedTo, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool PlayerObject_SetPos(void* player, void* object, float x, float y, float z) {
    return ompapi->PlayerObject.SetPos(player, object, x, y, z);
}

bool PlayerObject_GetPos(void* player, void* object, float* x, float* y, float* z) {
    return ompapi->PlayerObject.GetPos(player, object, x, y, z);
}

bool PlayerObject_SetRot(void* player, void* object, float rotationX, float rotationY, float rotationZ) {
    return ompapi->PlayerObject.SetRot(player, object, rotationX, rotationY, rotationZ);
}

bool PlayerObject_GetRot(void* player, void* object, float* rotationX, float* rotationY, float* rotationZ) {
    return ompapi->PlayerObject.GetRot(player, object, rotationX, rotationY, rotationZ);
}

int PlayerObject_GetModel(void* player, void* object) {
    return ompapi->PlayerObject.GetModel(player, object);
}

bool PlayerObject_SetNoCameraCollision(void* player, void* object) {
    return ompapi->PlayerObject.SetNoCameraCollision(player, object);
}

bool PlayerObject_IsValid(void* player, void* object) {
    return ompapi->PlayerObject.IsValid(player, object);
}

int PlayerObject_Move(void* player, void* object, float x, float y, float z, float speed, float rotationX, float rotationY, float rotationZ) {
    return ompapi->PlayerObject.Move(player, object, x, y, z, speed, rotationX, rotationY, rotationZ);
}

bool PlayerObject_Stop(void* player, void* object) {
    return ompapi->PlayerObject.Stop(player, object);
}

bool PlayerObject_IsMoving(void* player, void* object) {
    return ompapi->PlayerObject.IsMoving(player, object);
}

bool PlayerObject_BeginEditing(void* player, void* object) {
    return ompapi->PlayerObject.BeginEditing(player, object);
}

bool PlayerObject_SetMaterial(void* player, void* object, int materialIndex, int modelId, const char* textureLibrary, const char* textureName, uint32_t materialColor) {
    return ompapi->PlayerObject.SetMaterial(player, object, materialIndex, modelId, textureLibrary, textureName, materialColor);
}

bool PlayerObject_SetMaterialText(void* player, void* object, const char* text, int materialIndex, int materialSize, const char* fontface, int fontsize, bool bold, uint32_t fontColor, uint32_t backgroundColor, int textalignment) {
    return ompapi->PlayerObject.SetMaterialText(player, object, text, materialIndex, materialSize, fontface, fontsize, bold, fontColor, backgroundColor, textalignment);
}

float PlayerObject_GetDrawDistance(void* player, void* object) {
    return ompapi->PlayerObject.GetDrawDistance(player, object);
}

float PlayerObject_GetMoveSpeed(void* player, void* object) {
    return ompapi->PlayerObject.GetMoveSpeed(player, object);
}

bool PlayerObject_GetMovingTargetPos(void* player, void* object, float* targetX, float* targetY, float* targetZ) {
    return ompapi->PlayerObject.GetMovingTargetPos(player, object, targetX, targetY, targetZ);
}

bool PlayerObject_GetMovingTargetRot(void* player, void* object, float* rotationX, float* rotationY, float* rotationZ) {
    return ompapi->PlayerObject.GetMovingTargetRot(player, object, rotationX, rotationY, rotationZ);
}

bool PlayerObject_GetAttachedData(void* player, void* object, int* parentVehicle, int* parentObject, int* parentPlayer) {
    return ompapi->PlayerObject.GetAttachedData(player, object, parentVehicle, parentObject, parentPlayer);
}

bool PlayerObject_GetAttachedOffset(void* player, void* object, float* offsetX, float* offsetY, float* offsetZ, float* rotationX, float* rotationY, float* rotationZ) {
    return ompapi->PlayerObject.GetAttachedOffset(player, object, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ);
}

bool PlayerObject_GetSyncRotation(void* player, void* object) {
    return ompapi->PlayerObject.GetSyncRotation(player, object);
}

bool PlayerObject_IsMaterialSlotUsed(void* player, void* object, int materialIndex) {
    return ompapi->PlayerObject.IsMaterialSlotUsed(player, object, materialIndex);
}

bool PlayerObject_GetMaterial(void* player, void* object, int materialIndex, int* modelid, CAPIStringView* textureLibrary, CAPIStringView* textureName, int* materialColor) {
    return ompapi->PlayerObject.GetMaterial(player, object, materialIndex, modelid, textureLibrary, textureName, materialColor);
}

bool PlayerObject_GetMaterialText(void* player, void* object, int materialIndex, CAPIStringView* text, int* materialSize, CAPIStringView* fontFace, int* fontSize, bool* bold, int* fontColor, int* backgroundColor, int* textAlignment) {
    return ompapi->PlayerObject.GetMaterialText(player, object, materialIndex, text, materialSize, fontFace, fontSize, bold, fontColor, backgroundColor, textAlignment);
}

bool PlayerObject_IsNoCameraCollision(void* player, void* object) {
    return ompapi->PlayerObject.IsNoCameraCollision(player, object);
}


// Pickup functions

void* Pickup_Create(int model, int type, float x, float y, float z, int virtualWorld, int* id) {
    return ompapi->Pickup.Create(model, type, x, y, z, virtualWorld, id);
}

bool Pickup_AddStatic(int model, int type, float x, float y, float z, int virtualWorld) {
    return ompapi->Pickup.AddStatic(model, type, x, y, z, virtualWorld);
}

bool Pickup_Destroy(void* pickup) {
    return ompapi->Pickup.Destroy(pickup);
}

void* Pickup_FromID(int pickupid) {
    return ompapi->Pickup.FromID(pickupid);
}

int Pickup_GetID(void* pickup) {
    return ompapi->Pickup.GetID(pickup);
}

bool Pickup_IsValid(void* pickup) {
    return ompapi->Pickup.IsValid(pickup);
}

bool Pickup_IsStreamedIn(void* player, void* pickup) {
    return ompapi->Pickup.IsStreamedIn(player, pickup);
}

bool Pickup_GetPos(void* pickup, float* x, float* y, float* z) {
    return ompapi->Pickup.GetPos(pickup, x, y, z);
}

int Pickup_GetModel(void* pickup) {
    return ompapi->Pickup.GetModel(pickup);
}

int Pickup_GetType(void* pickup) {
    return ompapi->Pickup.GetType(pickup);
}

int Pickup_GetVirtualWorld(void* pickup) {
    return ompapi->Pickup.GetVirtualWorld(pickup);
}

bool Pickup_SetPos(void* pickup, float x, float y, float z, bool update) {
    return ompapi->Pickup.SetPos(pickup, x, y, z, update);
}

bool Pickup_SetModel(void* pickup, int model, bool update) {
    return ompapi->Pickup.SetModel(pickup, model, update);
}

bool Pickup_SetType(void* pickup, int type, bool update) {
    return ompapi->Pickup.SetType(pickup, type, update);
}

bool Pickup_SetVirtualWorld(void* pickup, int virtualworld) {
    return ompapi->Pickup.SetVirtualWorld(pickup, virtualworld);
}

bool Pickup_ShowForPlayer(void* player, void* pickup) {
    return ompapi->Pickup.ShowForPlayer(player, pickup);
}

bool Pickup_HideForPlayer(void* player, void* pickup) {
    return ompapi->Pickup.HideForPlayer(player, pickup);
}

bool Pickup_IsHiddenForPlayer(void* player, void* pickup) {
    return ompapi->Pickup.IsHiddenForPlayer(player, pickup);
}


// All functions

bool All_SendClientMessage(uint32_t color, const char* text) {
    return ompapi->All.SendClientMessage(color, text);
}

bool All_CreateExplosion(float x, float y, float z, int type, float radius) {
    return ompapi->All.CreateExplosion(x, y, z, type, radius);
}

bool All_SendDeathMessage(void* killer, void* killee, int weapon) {
    return ompapi->All.SendDeathMessage(killer, killee, weapon);
}

bool All_EnableStuntBonus(bool enable) {
    return ompapi->All.EnableStuntBonus(enable);
}


// Recording functions

bool Recording_Start(void* player, int type, const char* file) {
    return ompapi->Recording.Start(player, type, file);
}

bool Recording_Stop(void* player) {
    return ompapi->Recording.Stop(player);
}


// TextDraw functions

void* TextDraw_Create(float x, float y, const char* text, int* id) {
    return ompapi->TextDraw.Create(x, y, text, id);
}

bool TextDraw_Destroy(void* textdraw) {
    return ompapi->TextDraw.Destroy(textdraw);
}

void* TextDraw_FromID(int textdrawid) {
    return ompapi->TextDraw.FromID(textdrawid);
}

int TextDraw_GetID(void* textdraw) {
    return ompapi->TextDraw.GetID(textdraw);
}

bool TextDraw_IsValid(void* textdraw) {
    return ompapi->TextDraw.IsValid(textdraw);
}

bool TextDraw_IsVisibleForPlayer(void* player, void* textdraw) {
    return ompapi->TextDraw.IsVisibleForPlayer(player, textdraw);
}

bool TextDraw_SetLetterSize(void* textdraw, float sizeX, float sizeY) {
    return ompapi->TextDraw.SetLetterSize(textdraw, sizeX, sizeY);
}

bool TextDraw_SetTextSize(void* textdraw, float sizeX, float sizeY) {
    return ompapi->TextDraw.SetTextSize(textdraw, sizeX, sizeY);
}

bool TextDraw_SetAlignment(void* textdraw, int alignment) {
    return ompapi->TextDraw.SetAlignment(textdraw, alignment);
}

bool TextDraw_SetColor(void* textdraw, uint32_t color) {
    return ompapi->TextDraw.SetColor(textdraw, color);
}

bool TextDraw_SetUseBox(void* textdraw, bool use) {
    return ompapi->TextDraw.SetUseBox(textdraw, use);
}

bool TextDraw_SetBoxColor(void* textdraw, uint32_t color) {
    return ompapi->TextDraw.SetBoxColor(textdraw, color);
}

bool TextDraw_SetShadow(void* textdraw, int size) {
    return ompapi->TextDraw.SetShadow(textdraw, size);
}

bool TextDraw_SetOutline(void* textdraw, int size) {
    return ompapi->TextDraw.SetOutline(textdraw, size);
}

bool TextDraw_SetBackgroundColor(void* textdraw, uint32_t color) {
    return ompapi->TextDraw.SetBackgroundColor(textdraw, color);
}

bool TextDraw_SetFont(void* textdraw, int font) {
    return ompapi->TextDraw.SetFont(textdraw, font);
}

bool TextDraw_SetSetProportional(void* textdraw, bool set) {
    return ompapi->TextDraw.SetSetProportional(textdraw, set);
}

bool TextDraw_SetSelectable(void* textdraw, bool set) {
    return ompapi->TextDraw.SetSelectable(textdraw, set);
}

bool TextDraw_ShowForPlayer(void* player, void* textdraw) {
    return ompapi->TextDraw.ShowForPlayer(player, textdraw);
}

bool TextDraw_HideForPlayer(void* player, void* textdraw) {
    return ompapi->TextDraw.HideForPlayer(player, textdraw);
}

bool TextDraw_ShowForAll(void* textdraw) {
    return ompapi->TextDraw.ShowForAll(textdraw);
}

bool TextDraw_HideForAll(void* textdraw) {
    return ompapi->TextDraw.HideForAll(textdraw);
}

bool TextDraw_SetString(void* textdraw, const char* text) {
    return ompapi->TextDraw.SetString(textdraw, text);
}

bool TextDraw_SetPreviewModel(void* textdraw, int model) {
    return ompapi->TextDraw.SetPreviewModel(textdraw, model);
}

bool TextDraw_SetPreviewRot(void* textdraw, float rotationX, float rotationY, float rotationZ, float zoom) {
    return ompapi->TextDraw.SetPreviewRot(textdraw, rotationX, rotationY, rotationZ, zoom);
}

bool TextDraw_SetPreviewVehCol(void* textdraw, int color1, int color2) {
    return ompapi->TextDraw.SetPreviewVehCol(textdraw, color1, color2);
}

bool TextDraw_SetPos(void* textdraw, float x, float y) {
    return ompapi->TextDraw.SetPos(textdraw, x, y);
}

bool TextDraw_GetString(void* textdraw, CAPIStringView* text) {
    return ompapi->TextDraw.GetString(textdraw, text);
}

bool TextDraw_GetLetterSize(void* textdraw, float* sizeX, float* sizeY) {
    return ompapi->TextDraw.GetLetterSize(textdraw, sizeX, sizeY);
}

bool TextDraw_GetTextSize(void* textdraw, float* sizeX, float* sizeY) {
    return ompapi->TextDraw.GetTextSize(textdraw, sizeX, sizeY);
}

bool TextDraw_GetPos(void* textdraw, float* x, float* y) {
    return ompapi->TextDraw.GetPos(textdraw, x, y);
}

int TextDraw_GetColor(void* textdraw) {
    return ompapi->TextDraw.GetColor(textdraw);
}

int TextDraw_GetBoxColor(void* textdraw) {
    return ompapi->TextDraw.GetBoxColor(textdraw);
}

int TextDraw_GetBackgroundColor(void* textdraw) {
    return ompapi->TextDraw.GetBackgroundColor(textdraw);
}

int TextDraw_GetShadow(void* textdraw) {
    return ompapi->TextDraw.GetShadow(textdraw);
}

int TextDraw_GetOutline(void* textdraw) {
    return ompapi->TextDraw.GetOutline(textdraw);
}

int TextDraw_GetFont(void* textdraw) {
    return ompapi->TextDraw.GetFont(textdraw);
}

bool TextDraw_IsBox(void* textdraw) {
    return ompapi->TextDraw.IsBox(textdraw);
}

bool TextDraw_IsProportional(void* textdraw) {
    return ompapi->TextDraw.IsProportional(textdraw);
}

bool TextDraw_IsSelectable(void* textdraw) {
    return ompapi->TextDraw.IsSelectable(textdraw);
}

int TextDraw_GetAlignment(void* textdraw) {
    return ompapi->TextDraw.GetAlignment(textdraw);
}

int TextDraw_GetPreviewModel(void* textdraw) {
    return ompapi->TextDraw.GetPreviewModel(textdraw);
}

bool TextDraw_GetPreviewRot(void* textdraw, float* x, float* y, float* z, float* zoom) {
    return ompapi->TextDraw.GetPreviewRot(textdraw, x, y, z, zoom);
}

bool TextDraw_GetPreviewVehColor(void* textdraw, int* color1, int* color2) {
    return ompapi->TextDraw.GetPreviewVehColor(textdraw, color1, color2);
}

bool TextDraw_SetStringForPlayer(void* textdraw, void* player, const char* text) {
    return ompapi->TextDraw.SetStringForPlayer(textdraw, player, text);
}


// PlayerTextDraw functions

void* PlayerTextDraw_Create(void* player, float x, float y, const char* text, int* id) {
    return ompapi->PlayerTextDraw.Create(player, x, y, text, id);
}

bool PlayerTextDraw_Destroy(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.Destroy(player, textdraw);
}

void* PlayerTextDraw_FromID(void* player, int textdrawid) {
    return ompapi->PlayerTextDraw.FromID(player, textdrawid);
}

int PlayerTextDraw_GetID(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetID(player, textdraw);
}

bool PlayerTextDraw_IsValid(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.IsValid(player, textdraw);
}

bool PlayerTextDraw_IsVisible(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.IsVisible(player, textdraw);
}

bool PlayerTextDraw_SetLetterSize(void* player, void* textdraw, float x, float y) {
    return ompapi->PlayerTextDraw.SetLetterSize(player, textdraw, x, y);
}

bool PlayerTextDraw_SetTextSize(void* player, void* textdraw, float x, float y) {
    return ompapi->PlayerTextDraw.SetTextSize(player, textdraw, x, y);
}

bool PlayerTextDraw_SetAlignment(void* player, void* textdraw, int alignment) {
    return ompapi->PlayerTextDraw.SetAlignment(player, textdraw, alignment);
}

bool PlayerTextDraw_SetColor(void* player, void* textdraw, uint32_t color) {
    return ompapi->PlayerTextDraw.SetColor(player, textdraw, color);
}

bool PlayerTextDraw_UseBox(void* player, void* textdraw, bool use) {
    return ompapi->PlayerTextDraw.UseBox(player, textdraw, use);
}

bool PlayerTextDraw_SetBoxColor(void* player, void* textdraw, uint32_t color) {
    return ompapi->PlayerTextDraw.SetBoxColor(player, textdraw, color);
}

bool PlayerTextDraw_SetShadow(void* player, void* textdraw, int size) {
    return ompapi->PlayerTextDraw.SetShadow(player, textdraw, size);
}

bool PlayerTextDraw_SetOutline(void* player, void* textdraw, int size) {
    return ompapi->PlayerTextDraw.SetOutline(player, textdraw, size);
}

bool PlayerTextDraw_SetBackgroundColor(void* player, void* textdraw, uint32_t color) {
    return ompapi->PlayerTextDraw.SetBackgroundColor(player, textdraw, color);
}

bool PlayerTextDraw_SetFont(void* player, void* textdraw, int font) {
    return ompapi->PlayerTextDraw.SetFont(player, textdraw, font);
}

bool PlayerTextDraw_SetProportional(void* player, void* textdraw, bool set) {
    return ompapi->PlayerTextDraw.SetProportional(player, textdraw, set);
}

bool PlayerTextDraw_SetSelectable(void* player, void* textdraw, bool set) {
    return ompapi->PlayerTextDraw.SetSelectable(player, textdraw, set);
}

bool PlayerTextDraw_Show(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.Show(player, textdraw);
}

bool PlayerTextDraw_Hide(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.Hide(player, textdraw);
}

bool PlayerTextDraw_SetString(void* player, void* textdraw, const char* text) {
    return ompapi->PlayerTextDraw.SetString(player, textdraw, text);
}

bool PlayerTextDraw_SetPreviewModel(void* player, void* textdraw, int model) {
    return ompapi->PlayerTextDraw.SetPreviewModel(player, textdraw, model);
}

bool PlayerTextDraw_SetPreviewRot(void* player, void* textdraw, float rx, float ry, float rz, float zoom) {
    return ompapi->PlayerTextDraw.SetPreviewRot(player, textdraw, rx, ry, rz, zoom);
}

bool PlayerTextDraw_SetPreviewVehCol(void* player, void* textdraw, int color1, int color2) {
    return ompapi->PlayerTextDraw.SetPreviewVehCol(player, textdraw, color1, color2);
}

bool PlayerTextDraw_SetPos(void* player, void* textdraw, float x, float y) {
    return ompapi->PlayerTextDraw.SetPos(player, textdraw, x, y);
}

bool PlayerTextDraw_GetString(void* player, void* textdraw, CAPIStringView* text) {
    return ompapi->PlayerTextDraw.GetString(player, textdraw, text);
}

bool PlayerTextDraw_GetLetterSize(void* player, void* textdraw, float* x, float* y) {
    return ompapi->PlayerTextDraw.GetLetterSize(player, textdraw, x, y);
}

bool PlayerTextDraw_GetTextSize(void* player, void* textdraw, float* x, float* y) {
    return ompapi->PlayerTextDraw.GetTextSize(player, textdraw, x, y);
}

bool PlayerTextDraw_GetPos(void* player, void* textdraw, float* x, float* y) {
    return ompapi->PlayerTextDraw.GetPos(player, textdraw, x, y);
}

int PlayerTextDraw_GetColor(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetColor(player, textdraw);
}

int PlayerTextDraw_GetBoxColor(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetBoxColor(player, textdraw);
}

int PlayerTextDraw_GetBackgroundColor(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetBackgroundColor(player, textdraw);
}

int PlayerTextDraw_GetShadow(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetShadow(player, textdraw);
}

int PlayerTextDraw_GetOutline(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetOutline(player, textdraw);
}

int PlayerTextDraw_GetFont(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetFont(player, textdraw);
}

bool PlayerTextDraw_IsBox(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.IsBox(player, textdraw);
}

bool PlayerTextDraw_IsProportional(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.IsProportional(player, textdraw);
}

bool PlayerTextDraw_IsSelectable(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.IsSelectable(player, textdraw);
}

int PlayerTextDraw_GetAlignment(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetAlignment(player, textdraw);
}

int PlayerTextDraw_GetPreviewModel(void* player, void* textdraw) {
    return ompapi->PlayerTextDraw.GetPreviewModel(player, textdraw);
}

bool PlayerTextDraw_GetPreviewRot(void* player, void* textdraw, float* rx, float* ry, float* rz, float* zoom) {
    return ompapi->PlayerTextDraw.GetPreviewRot(player, textdraw, rx, ry, rz, zoom);
}

bool PlayerTextDraw_GetPreviewVehColor(void* player, void* textdraw, int* color1, int* color2) {
    return ompapi->PlayerTextDraw.GetPreviewVehColor(player, textdraw, color1, color2);
}


// TextLabel functions

void* TextLabel_Create(const char* text, uint32_t color, float x, float y, float z, float drawDistance, int virtualWorld, bool los, int* id) {
    return ompapi->TextLabel.Create(text, color, x, y, z, drawDistance, virtualWorld, los, id);
}

bool TextLabel_Destroy(void* textlabel) {
    return ompapi->TextLabel.Destroy(textlabel);
}

void* TextLabel_FromID(int textlabelid) {
    return ompapi->TextLabel.FromID(textlabelid);
}

int TextLabel_GetID(void* textlabel) {
    return ompapi->TextLabel.GetID(textlabel);
}

bool TextLabel_AttachToPlayer(void* textlabel, void* player, float offsetX, float offsetY, float offsetZ) {
    return ompapi->TextLabel.AttachToPlayer(textlabel, player, offsetX, offsetY, offsetZ);
}

bool TextLabel_AttachToVehicle(void* textlabel, void* vehicle, float offsetX, float offsetY, float offsetZ) {
    return ompapi->TextLabel.AttachToVehicle(textlabel, vehicle, offsetX, offsetY, offsetZ);
}

bool TextLabel_UpdateText(void* textlabel, uint32_t color, const char* text) {
    return ompapi->TextLabel.UpdateText(textlabel, color, text);
}

bool TextLabel_IsValid(void* textlabel) {
    return ompapi->TextLabel.IsValid(textlabel);
}

bool TextLabel_IsStreamedIn(void* player, void* textlabel) {
    return ompapi->TextLabel.IsStreamedIn(player, textlabel);
}

bool TextLabel_GetText(void* textlabel, CAPIStringView* output) {
    return ompapi->TextLabel.GetText(textlabel, output);
}

uint32_t TextLabel_GetColor(void* textlabel) {
    return ompapi->TextLabel.GetColor(textlabel);
}

bool TextLabel_GetPos(void* textlabel, float* x, float* y, float* z) {
    return ompapi->TextLabel.GetPos(textlabel, x, y, z);
}

bool TextLabel_SetDrawDistance(void* textlabel, float distance) {
    return ompapi->TextLabel.SetDrawDistance(textlabel, distance);
}

float TextLabel_GetDrawDistance(void* textlabel) {
    return ompapi->TextLabel.GetDrawDistance(textlabel);
}

bool TextLabel_GetLOS(void* textlabel) {
    return ompapi->TextLabel.GetLOS(textlabel);
}

bool TextLabel_SetLOS(void* textlabel, bool status) {
    return ompapi->TextLabel.SetLOS(textlabel, status);
}

int TextLabel_GetVirtualWorld(void* textlabel) {
    return ompapi->TextLabel.GetVirtualWorld(textlabel);
}

bool TextLabel_SetVirtualWorld(void* textlabel, int world) {
    return ompapi->TextLabel.SetVirtualWorld(textlabel, world);
}

bool TextLabel_GetAttachedData(void* textlabel, int* attached_player, int* attached_vehicle) {
    return ompapi->TextLabel.GetAttachedData(textlabel, attached_player, attached_vehicle);
}


// PlayerTextLabel functions

void* PlayerTextLabel_Create(void* player, const char* text, uint32_t color, float x, float y, float z, float drawDistance, void* attachedPlayer, void* attachedVehicle, bool los, int* id) {
    return ompapi->PlayerTextLabel.Create(player, text, color, x, y, z, drawDistance, attachedPlayer, attachedVehicle, los, id);
}

bool PlayerTextLabel_Destroy(void* player, void* textlabel) {
    return ompapi->PlayerTextLabel.Destroy(player, textlabel);
}

void* PlayerTextLabel_FromID(void* player, int textlabelid) {
    return ompapi->PlayerTextLabel.FromID(player, textlabelid);
}

int PlayerTextLabel_GetID(void* player, void* textlabel) {
    return ompapi->PlayerTextLabel.GetID(player, textlabel);
}

bool PlayerTextLabel_UpdateText(void* player, void* textlabel, uint32_t color, const char* text) {
    return ompapi->PlayerTextLabel.UpdateText(player, textlabel, color, text);
}

bool PlayerTextLabel_IsValid(void* player, void* textlabel, bool* valid) {
    return ompapi->PlayerTextLabel.IsValid(player, textlabel, valid);
}

bool PlayerTextLabel_GetText(void* player, void* textlabel, CAPIStringView* output) {
    return ompapi->PlayerTextLabel.GetText(player, textlabel, output);
}

bool PlayerTextLabel_GetColor(void* player, void* textlabel, uint32_t* color) {
    return ompapi->PlayerTextLabel.GetColor(player, textlabel, color);
}

bool PlayerTextLabel_GetPos(void* player, void* textlabel, float* x, float* y, float* z) {
    return ompapi->PlayerTextLabel.GetPos(player, textlabel, x, y, z);
}

bool PlayerTextLabel_SetDrawDistance(void* player, void* textlabel, float distance) {
    return ompapi->PlayerTextLabel.SetDrawDistance(player, textlabel, distance);
}

float PlayerTextLabel_GetDrawDistance(void* player, void* textlabel) {
    return ompapi->PlayerTextLabel.GetDrawDistance(player, textlabel);
}

bool PlayerTextLabel_GetLOS(void* player, void* textlabel) {
    return ompapi->PlayerTextLabel.GetLOS(player, textlabel);
}

bool PlayerTextLabel_SetLOS(void* player, void* textlabel, bool status) {
    return ompapi->PlayerTextLabel.SetLOS(player, textlabel, status);
}

int PlayerTextLabel_GetVirtualWorld(void* player) {
    return ompapi->PlayerTextLabel.GetVirtualWorld(player);
}

bool PlayerTextLabel_GetAttachedData(void* player, void* textlabel, int* attached_player, int* attached_vehicle) {
    return ompapi->PlayerTextLabel.GetAttachedData(player, textlabel, attached_player, attached_vehicle);
}


// Vehicle functions

void* Vehicle_Create(int modelid, float x, float y, float z, float rotation, int color1, int color2, int respawnDelay, bool addSiren, int* id) {
    return ompapi->Vehicle.Create(modelid, x, y, z, rotation, color1, color2, respawnDelay, addSiren, id);
}

bool Vehicle_Destroy(void* vehicle) {
    return ompapi->Vehicle.Destroy(vehicle);
}

void* Vehicle_FromID(int vehicleid) {
    return ompapi->Vehicle.FromID(vehicleid);
}

int Vehicle_GetID(void* vehicle) {
    return ompapi->Vehicle.GetID(vehicle);
}

int Vehicle_GetMaxPassengerSeats(int modelid) {
    return ompapi->Vehicle.GetMaxPassengerSeats(modelid);
}

bool Vehicle_IsStreamedIn(void* vehicle, void* player) {
    return ompapi->Vehicle.IsStreamedIn(vehicle, player);
}

bool Vehicle_GetPos(void* vehicle, float* x, float* y, float* z) {
    return ompapi->Vehicle.GetPos(vehicle, x, y, z);
}

bool Vehicle_SetPos(void* vehicle, float x, float y, float z) {
    return ompapi->Vehicle.SetPos(vehicle, x, y, z);
}

float Vehicle_GetZAngle(void* vehicle) {
    return ompapi->Vehicle.GetZAngle(vehicle);
}

bool Vehicle_GetRotationQuat(void* vehicle, float* w, float* x, float* y, float* z) {
    return ompapi->Vehicle.GetRotationQuat(vehicle, w, x, y, z);
}

float Vehicle_GetDistanceFromPoint(void* vehicle, float x, float y, float z) {
    return ompapi->Vehicle.GetDistanceFromPoint(vehicle, x, y, z);
}

bool Vehicle_SetZAngle(void* vehicle, float angle) {
    return ompapi->Vehicle.SetZAngle(vehicle, angle);
}

bool Vehicle_SetParamsForPlayer(void* vehicle, void* player, int objective, int doors) {
    return ompapi->Vehicle.SetParamsForPlayer(vehicle, player, objective, doors);
}

bool Vehicle_UseManualEngineAndLights() {
    return ompapi->Vehicle.UseManualEngineAndLights();
}

bool Vehicle_SetParamsEx(void* vehicle, int engine, int lights, int alarm, int doors, int bonnet, int boot, int objective) {
    return ompapi->Vehicle.SetParamsEx(vehicle, engine, lights, alarm, doors, bonnet, boot, objective);
}

bool Vehicle_GetParamsEx(void* vehicle, int* engine, int* lights, int* alarm, int* doors, int* bonnet, int* boot, int* objective) {
    return ompapi->Vehicle.GetParamsEx(vehicle, engine, lights, alarm, doors, bonnet, boot, objective);
}

int Vehicle_GetParamsSirenState(void* vehicle) {
    return ompapi->Vehicle.GetParamsSirenState(vehicle);
}

bool Vehicle_SetParamsCarDoors(void* vehicle, int frontLeft, int frontRight, int rearLeft, int rearRight) {
    return ompapi->Vehicle.SetParamsCarDoors(vehicle, frontLeft, frontRight, rearLeft, rearRight);
}

bool Vehicle_GetParamsCarDoors(void* vehicle, int* frontLeft, int* frontRight, int* rearLeft, int* rearRight) {
    return ompapi->Vehicle.GetParamsCarDoors(vehicle, frontLeft, frontRight, rearLeft, rearRight);
}

bool Vehicle_SetParamsCarWindows(void* vehicle, int frontLeft, int frontRight, int rearLeft, int rearRight) {
    return ompapi->Vehicle.SetParamsCarWindows(vehicle, frontLeft, frontRight, rearLeft, rearRight);
}

bool Vehicle_GetParamsCarWindows(void* vehicle, int* frontLeft, int* frontRight, int* rearLeft, int* rearRight) {
    return ompapi->Vehicle.GetParamsCarWindows(vehicle, frontLeft, frontRight, rearLeft, rearRight);
}

bool Vehicle_SetToRespawn(void* vehicle) {
    return ompapi->Vehicle.SetToRespawn(vehicle);
}

bool Vehicle_LinkToInterior(void* vehicle, int interiorid) {
    return ompapi->Vehicle.LinkToInterior(vehicle, interiorid);
}

bool Vehicle_AddComponent(void* vehicle, int componentid) {
    return ompapi->Vehicle.AddComponent(vehicle, componentid);
}

bool Vehicle_RemoveComponent(void* vehicle, int componentid) {
    return ompapi->Vehicle.RemoveComponent(vehicle, componentid);
}

bool Vehicle_ChangeColor(void* vehicle, int color1, int color2) {
    return ompapi->Vehicle.ChangeColor(vehicle, color1, color2);
}

bool Vehicle_ChangePaintjob(void* vehicle, int paintjobid) {
    return ompapi->Vehicle.ChangePaintjob(vehicle, paintjobid);
}

bool Vehicle_SetHealth(void* vehicle, float health) {
    return ompapi->Vehicle.SetHealth(vehicle, health);
}

float Vehicle_GetHealth(void* vehicle) {
    return ompapi->Vehicle.GetHealth(vehicle);
}

bool Vehicle_AttachTrailer(void* trailer, void* vehicle) {
    return ompapi->Vehicle.AttachTrailer(trailer, vehicle);
}

bool Vehicle_DetachTrailer(void* vehicle) {
    return ompapi->Vehicle.DetachTrailer(vehicle);
}

bool Vehicle_IsTrailerAttached(void* vehicle) {
    return ompapi->Vehicle.IsTrailerAttached(vehicle);
}

void* Vehicle_GetTrailer(void* vehicle) {
    return ompapi->Vehicle.GetTrailer(vehicle);
}

bool Vehicle_SetNumberPlate(void* vehicle, const char* numberPlate) {
    return ompapi->Vehicle.SetNumberPlate(vehicle, numberPlate);
}

int Vehicle_GetModel(void* vehicle) {
    return ompapi->Vehicle.GetModel(vehicle);
}

int Vehicle_GetComponentInSlot(void* vehicle, int slot) {
    return ompapi->Vehicle.GetComponentInSlot(vehicle, slot);
}

int Vehicle_GetComponentType(int componentid) {
    return ompapi->Vehicle.GetComponentType(componentid);
}

bool Vehicle_CanHaveComponent(int modelid, int componentid) {
    return ompapi->Vehicle.CanHaveComponent(modelid, componentid);
}

bool Vehicle_GetRandomColorPair(int modelid, int* color1, int* color2, int* color3, int* color4) {
    return ompapi->Vehicle.GetRandomColorPair(modelid, color1, color2, color3, color4);
}

int Vehicle_ColorIndexToColor(int colorIndex, int alpha) {
    return ompapi->Vehicle.ColorIndexToColor(colorIndex, alpha);
}

bool Vehicle_Repair(void* vehicle) {
    return ompapi->Vehicle.Repair(vehicle);
}

bool Vehicle_GetVelocity(void* vehicle, float* x, float* y, float* z) {
    return ompapi->Vehicle.GetVelocity(vehicle, x, y, z);
}

bool Vehicle_SetVelocity(void* vehicle, float x, float y, float z) {
    return ompapi->Vehicle.SetVelocity(vehicle, x, y, z);
}

bool Vehicle_SetAngularVelocity(void* vehicle, float x, float y, float z) {
    return ompapi->Vehicle.SetAngularVelocity(vehicle, x, y, z);
}

bool Vehicle_GetDamageStatus(void* vehicle, int* panels, int* doors, int* lights, int* tires) {
    return ompapi->Vehicle.GetDamageStatus(vehicle, panels, doors, lights, tires);
}

bool Vehicle_UpdateDamageStatus(void* vehicle, int panels, int doors, int lights, int tires) {
    return ompapi->Vehicle.UpdateDamageStatus(vehicle, panels, doors, lights, tires);
}

bool Vehicle_GetModelInfo(int vehiclemodel, int infotype, float* x, float* y, float* z) {
    return ompapi->Vehicle.GetModelInfo(vehiclemodel, infotype, x, y, z);
}

bool Vehicle_SetVirtualWorld(void* vehicle, int virtualWorld) {
    return ompapi->Vehicle.SetVirtualWorld(vehicle, virtualWorld);
}

int Vehicle_GetVirtualWorld(void* vehicle) {
    return ompapi->Vehicle.GetVirtualWorld(vehicle);
}

int Vehicle_GetLandingGearState(void* vehicle) {
    return ompapi->Vehicle.GetLandingGearState(vehicle);
}

bool Vehicle_IsValid(void* vehicle) {
    return ompapi->Vehicle.IsValid(vehicle);
}

void* Vehicle_AddStatic(int modelid, float x, float y, float z, float angle, int color1, int color2, int* id) {
    return ompapi->Vehicle.AddStatic(modelid, x, y, z, angle, color1, color2, id);
}

void* Vehicle_AddStaticEx(int modelid, float x, float y, float z, float angle, int color1, int color2, int respawnDelay, bool addSiren, int* id) {
    return ompapi->Vehicle.AddStaticEx(modelid, x, y, z, angle, color1, color2, respawnDelay, addSiren, id);
}

bool Vehicle_EnableFriendlyFire() {
    return ompapi->Vehicle.EnableFriendlyFire();
}

bool Vehicle_GetSpawnInfo(void* vehicle, float* x, float* y, float* z, float* rotation, int* color1, int* color2) {
    return ompapi->Vehicle.GetSpawnInfo(vehicle, x, y, z, rotation, color1, color2);
}

bool Vehicle_SetSpawnInfo(void* vehicle, int modelid, float x, float y, float z, float rotation, int color1, int color2, int respawn_time, int interior) {
    return ompapi->Vehicle.SetSpawnInfo(vehicle, modelid, x, y, z, rotation, color1, color2, respawn_time, interior);
}

int Vehicle_GetModelCount(int modelid) {
    return ompapi->Vehicle.GetModelCount(modelid);
}

int Vehicle_GetModelsUsed() {
    return ompapi->Vehicle.GetModelsUsed();
}

int Vehicle_GetPaintjob(void* vehicle) {
    return ompapi->Vehicle.GetPaintjob(vehicle);
}

bool Vehicle_GetColor(void* vehicle, int* color1, int* color2) {
    return ompapi->Vehicle.GetColor(vehicle, color1, color2);
}

int Vehicle_GetInterior(void* vehicle) {
    return ompapi->Vehicle.GetInterior(vehicle);
}

bool Vehicle_GetNumberPlate(void* vehicle, CAPIStringView* numberPlate) {
    return ompapi->Vehicle.GetNumberPlate(vehicle, numberPlate);
}

bool Vehicle_SetRespawnDelay(void* vehicle, int respawn_delay) {
    return ompapi->Vehicle.SetRespawnDelay(vehicle, respawn_delay);
}

int Vehicle_GetRespawnDelay(void* vehicle) {
    return ompapi->Vehicle.GetRespawnDelay(vehicle);
}

void* Vehicle_GetCab(void* vehicle) {
    return ompapi->Vehicle.GetCab(vehicle);
}

void* Vehicle_GetTower(void* vehicle) {
    return ompapi->Vehicle.GetTower(vehicle);
}

int Vehicle_GetOccupiedTick(void* vehicle) {
    return ompapi->Vehicle.GetOccupiedTick(vehicle);
}

int Vehicle_GetRespawnTick(void* vehicle) {
    return ompapi->Vehicle.GetRespawnTick(vehicle);
}

bool Vehicle_HasBeenOccupied(void* vehicle) {
    return ompapi->Vehicle.HasBeenOccupied(vehicle);
}

bool Vehicle_IsOccupied(void* vehicle) {
    return ompapi->Vehicle.IsOccupied(vehicle);
}

bool Vehicle_IsDead(void* vehicle) {
    return ompapi->Vehicle.IsDead(vehicle);
}

bool Vehicle_SetParamsSirenState(void* vehicle, bool siren_state) {
    return ompapi->Vehicle.SetParamsSirenState(vehicle, siren_state);
}

bool Vehicle_ToggleSirenEnabled(void* vehicle, bool status) {
    return ompapi->Vehicle.ToggleSirenEnabled(vehicle, status);
}

bool Vehicle_IsSirenEnabled(void* vehicle) {
    return ompapi->Vehicle.IsSirenEnabled(vehicle);
}

void* Vehicle_GetLastDriver(void* vehicle) {
    return ompapi->Vehicle.GetLastDriver(vehicle);
}

void* Vehicle_GetDriver(void* vehicle) {
    return ompapi->Vehicle.GetDriver(vehicle);
}

int Vehicle_GetSirenState(void* vehicle) {
    return ompapi->Vehicle.GetSirenState(vehicle);
}

uint32_t Vehicle_GetHydraReactorAngle(void* vehicle) {
    return ompapi->Vehicle.GetHydraReactorAngle(vehicle);
}

float Vehicle_GetTrainSpeed(void* vehicle) {
    return ompapi->Vehicle.GetTrainSpeed(vehicle);
}

bool Vehicle_GetMatrix(void* vehicle, float* rightX, float* rightY, float* rightZ, float* upX, float* upY, float* upZ, float* atX, float* atY, float* atZ) {
    return ompapi->Vehicle.GetMatrix(vehicle, rightX, rightY, rightZ, upX, upY, upZ, atX, atY, atZ);
}

void* Vehicle_GetOccupant(void* vehicle, int seat) {
    return ompapi->Vehicle.GetOccupant(vehicle, seat);
}

int Vehicle_CountOccupants(void* vehicle) {
    return ompapi->Vehicle.CountOccupants(vehicle);
}
